rules:
  default:
    disabling_label: "do not merge"
    protection:
      required_status_checks:
        strict: true
        strict_method: rebase
        contexts:
          - continuous-integration/travis-ci
      required_pull_request_reviews:
        required_approving_review_count: 2
