pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
  conditions:
  - label!=do not merge
  - '#approved-reviews-by>=1'
  - status-success=continuous-integration/travis-ci/pr
  name: default
