os:
  - linux

branches:
  only:
    - master
language: python

matrix:
    include:
        - python: 3.6
          env: TASK=fmt
        - python: 3.6
          env: TASK=lint
        - python: 3.6
          env: TASK=test
        - python: 3.6
          env: TASK=coverage
        - python: 3.5
          env: TASK=test
        - python: 3.5
          env: TASK=coverage
        - python: 3.4
          env: TASK=test
        - python: 3.4
          env: TASK=coverage

script:
    - make -f Makefile $TASK
